# Generated by Django 4.2.5 on 2024-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('job2', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('project_completed', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='portfolio_images/')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('clients', models.PositiveIntegerField()),
                ('facebook', models.URLField(max_length=500)),
                ('twitter', models.URLField(max_length=500)),
                ('instagram', models.URLField(max_length=500)),
            ],
        ),
    ]
