# Generated by Django 4.2.5 on 2024-06-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
