# Generated by Django 4.2.5 on 2024-06-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0003_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('detail_url', models.URLField()),
                ('icon_class', models.CharField(default='flaticon-up-right-arrow', max_length=50)),
            ],
        ),
    ]
