# Generated by Django 4.2.5 on 2024-06-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (e.g., Apps, Branding)', max_length=50)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the category', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the portfolio project', max_length=100)),
                ('description', models.TextField(help_text='Short description of the project')),
                ('image', models.ImageField(help_text='Image representing the project', upload_to='portfolios/images/')),
                ('detail_url', models.URLField(blank=True, help_text='URL to the project details (optional)')),
                ('category', models.ForeignKey(help_text='Category of the project', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='pot.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
