# Generated by Django 4.2.5 on 2024-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0007_category_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='phone_number',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
