# Generated by Django 4.2.5 on 2024-06-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0008_home_address_home_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('services', models.CharField(choices=[('Web Development', 'Web Development'), ('Graphics Design', 'Graphics Design'), ('App Design', 'App Design'), ('Training', 'Training')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
