# Generated by Django 4.2.5 on 2024-06-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0009_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pot.service'),
        ),
    ]
