# Generated by Django 4.2.5 on 2024-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0013_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='exist', upload_to='portfolio_images/'),
            preserve_default=False,
        ),
    ]
