# Generated by Django 4.2.5 on 2024-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0014_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(choices=[('wb', 'Web_Development'), ('ap', 'App_Development'), ('od', 'Others')], max_length=2),
        ),
    ]
