# Generated by Django 4.2.5 on 2024-06-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0015_alter_contact_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
