# Generated by Django 4.2.5 on 2024-06-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0016_alter_blog_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='date',
        ),
    ]
