# Generated by Django 4.2.5 on 2024-06-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0017_alter_blog_options_rename_published_date_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='facebook',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='instagram',
            new_name='telegram',
        ),
        migrations.AddField(
            model_name='home',
            name='whatsapp',
            field=models.URLField(default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
