# Generated by Django 4.2.5 on 2024-06-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0019_home_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cv',
            field=models.FileField(upload_to='portfolio_images/'),
        ),
    ]
