# Generated by Django 4.2.5 on 2024-06-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0022_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='whatsapp_number',
            new_name='phone_number',
        ),
    ]
