# Generated by Django 4.2.5 on 2024-06-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0023_rename_whatsapp_number_contacts_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
