# Generated by Django 4.2.5 on 2024-06-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0028_contact_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
